name: flow-match
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.*
  - scipy=1.12.*
  - matplotlib=3.8.*
  - jupyter
  - jupyterlab
  - ipykernel
  - tqdm
  - pandas=2.2.*
  - pip:
    - torch==2.2.2
    - torch-geometric==2.5.3
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - rdkit==2023.09.5
    - MDAnalysis==2.7.0
    - torchdiffeq==0.2.3
    - wandb==0.16.*
    - py3Dmol==2.1.*
    - nglview==3.1.*
    - pytest==8.1.*
